# Exploratory Data Analysis

## Task #1: Diabetes Variable

In [8]:
import pandas as pd
from scipy import stats

In [9]:
df = pd.read_csv('https://raw.githubusercontent.com/juanklopper/TutorialData/main/heart_failure.csv')

In [10]:
df.head()

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,hypertension,platelets,serum_creatinine,serum_sodium,sex,smoking,time,death
0,75.0,No,582,No,20,Yes,265000.00,1.9,130,Male,No,4,Yes
1,55.0,No,7861,No,38,No,263358.03,1.1,136,Male,No,6,Yes
2,65.0,No,146,No,20,No,162000.00,1.3,129,Male,Yes,7,Yes
3,50.0,Yes,111,No,20,No,210000.00,1.9,137,Male,No,7,Yes
4,65.0,Yes,160,Yes,20,No,327000.00,2.7,116,Female,No,8,Yes

In [12]:
df['diabetes'].unique()

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [16]:
df.diabetes.value_counts()

diabetes
No     174
Yes    125
Name: count, dtype: int64

In [14]:
df.diabetes.value_counts(normalize=True)

diabetes
No     0.58194
Yes    0.41806
Name: proportion, dtype: float64

## Task #2: Generating a Contingency Table

In [17]:
pd.crosstab(df.death, df.anaemia, normalize=True) * 100

anaemia         No        Yes
death
No       40.133779  27.759197
Yes      16.722408  15.384615

## Task #3: Finding the Median

In [20]:
df.groupby('anaemia')['ejection_fraction'].median()

anaemia
No     38.0
Yes    38.0
Name: ejection_fraction, dtype: float64

## Task #4: Finding the Variance

In [21]:
df.groupby('anaemia').age.var(ddof=1)

anaemia
No     141.763348
Yes    139.675064
Name: age, dtype: float64

## Quiz Questions

##### 1. By writing

In [ ]:
import panada as pd

##### 2. By writing

In [ ]:
pd.read_csv('filename.csv')

##### 3. By writing

In [ ]:
df.head()

##### 4. By writing

In [ ]:
df['Age'].mean()

##### 5. By writing

In [ ]:
df['Salary'].median()

##### 6. By writing

In [ ]:
df['Score'].std()

##### 7. By writing

In [ ]:
df.isnull().sum()

##### 8. By writing

In [ ]:
df['Age'].corr(df['Salary'])

##### 9. By writing

In [ ]:
df[df['Age'] > 30]

##### 10. By writing

In [ ]:
df['Score'].max() - df['Score'].min()

##### 11. By writing

In [ ]:
df.groupby('Department')['Salary'].mean()

##### 12. By writing

In [ ]:
df.groupby(['Department', 'Job Title']).size()

##### 13. By writing

In [ ]:
df.groupby('Department')['Age'].max()

##### 14. By writing

In [ ]:
pd.crosstab(df['Department'], df['Job Title'])

##### 15. By writing

In [ ]:
pd.crosstab(df['Department'], df['Job Title'], values=df['Salary'], aggfunc='mean')